const TESTS = [
{
  id: "queen-bohemian-rhapsody",
  questId: "Quest Video 25",
  category: "Queen",
  difficulty: "Advanced",
  title: "Queen - Bohemian Rhapsody (Lyrics)",
  youtubeId: "fJ9rUzIMcZQ",
  durationHint: 355,
  description: "Queen's iconic multi-section rock epic 'Bohemian Rhapsody'.",
  questions: [
    { at: 0,   tier: 1, q: "Is this the _____ life?", options: ["real", "true", "actual", "right"], correct: 0 },
    { at: 5,   tier: 1, q: "Is this just _____?", options: ["fantasy", "fiction", "a dream", "imagination"], correct: 0 },
    { at: 11,  tier: 2, q: "Caught in a _____, no escape from reality", options: ["landslide", "downpour", "storm", "nightmare"], correct: 0 },
    { at: 19,  tier: 2, q: "Open your eyes, look up to the _____ and see", options: ["skies", "stars", "clouds", "moon"], correct: 0 },
    { at: 27,  tier: 1, q: "I'm just a poor _____, I need no sympathy", options: ["boy", "man", "soul", "child"], correct: 0 },
    { at: 36,  tier: 2, q: "Because I'm easy come, easy _____", options: ["go", "leave", "fall", "move"], correct: 0 },
    { at: 42,  tier: 1, q: "Little _____, little low", options: ["high", "up", "down", "far"], correct: 0 },
    { at: 48,  tier: 2, q: "Any way the wind blows doesn't really _____ to me, to me", options: ["matter", "belong", "mean", "apply"], correct: 0 },

    { at: 61,  tier: 1, q: "Mama, just killed a _____", options: ["man", "boy", "stranger", "soldier"], correct: 0 },
    { at: 67,  tier: 3, q: "Put a gun against his head, pulled my _____, now he's dead", options: ["trigger", "weapon", "gun", "finger"], correct: 0 },
    { at: 77,  tier: 1, q: "Mama, life had just _____", options: ["begun", "started", "changed", "ended"], correct: 0 },
    { at: 84,  tier: 2, q: "But now I've gone and thrown it all _____", options: ["away", "down", "out", "over"], correct: 0 },
    { at: 92,  tier: 2, q: "Mama, ooh, didn't mean to make you _____", options: ["cry", "sad", "angry", "weep"], correct: 0 },
    { at: 99,  tier: 3, q: "If I'm not back again this time _____", options: ["tomorrow", "tonight", "next week", "again"], correct: 0 },
    { at: 108, tier: 2, q: "Carry on, carry on as if nothing really _____", options: ["matters", "happened", "changed", "remains"], correct: 0 },

    { at: 122, tier: 2, q: "Too late, my time has _____", options: ["come", "gone", "passed", "ended"], correct: 0 },
    { at: 129, tier: 3, q: "Sends shivers down my spine, body's aching all the _____", options: ["time", "day", "night", "while"], correct: 0 },
    { at: 139, tier: 1, q: "Goodbye, everybody, I've got to _____", options: ["go", "leave", "run", "die"], correct: 0 },
    { at: 147, tier: 2, q: "Gotta leave you all behind and face the _____", options: ["truth", "future", "music", "end"], correct: 0 },
    { at: 155, tier: 2, q: "Mama, ooh (any way the wind _____)", options: ["blows", "goes", "flows", "moves"], correct: 0 },
    { at: 162, tier: 2, q: "I don't wanna _____", options: ["die", "go", "leave", "cry"], correct: 0 },
    { at: 169, tier: 3, q: "I sometimes wish I'd never been _____ at all", options: ["born", "alive", "here", "there"], correct: 0 },

    { at: 181, tier: 2, q: "I see a little silhouetto of a _____", options: ["man", "boy", "figure", "stranger"], correct: 0 },
    { at: 190, tier: 3, q: "Scaramouche, Scaramouche, will you do the _____?", options: ["Fandango", "Tango", "Waltz", "Flamenco"], correct: 0 },
    { at: 200, tier: 2, q: "Thunderbolt and lightning, very, very _____ me", options: ["frightening", "scaring", "terrifying", "alarming"], correct: 0 },
    { at: 211, tier: 3, q: "(Galileo) Galileo, (Galileo) Galileo, Galileo Figaro, _____", options: ["magnifico", "magnifico!", "bravissimo", "fantastico"], correct: 0 },
    { at: 224, tier: 2, q: "But I'm just a poor boy, nobody _____ me", options: ["loves", "knows", "needs", "helps"], correct: 0 },
    { at: 234, tier: 2, q: "He's just a poor boy from a poor _____", options: ["family", "country", "home", "village"], correct: 0 },
    { at: 243, tier: 3, q: "Spare him his life from this _____", options: ["monstrosity", "misery", "tragedy", "madness"], correct: 0 },

    { at: 255, tier: 1, q: "Easy come, easy _____, will you let me go?", options: ["go", "leave", "fall", "move"], correct: 0 },
    { at: 262, tier: 3, q: "_____", options: ["Bismillah", "Galileo", "Magnifico", "Scaramouche"], correct: 0 },
    { at: 268, tier: 2, q: "No, we will not let you _____ (let him go)", options: ["go", "leave", "escape", "run"], correct: 0 },
    { at: 276, tier: 3, q: "Bismillah, we will not let you _____ (let him go)", options: ["go", "leave", "escape", "run"], correct: 0 },
    { at: 284, tier: 3, q: "Bismillah, we will not let you _____ (let me go)", options: ["go", "leave", "escape", "run"], correct: 0 },
    { at: 292, tier: 2, q: "Will not let you go (let me _____)", options: ["go", "leave", "escape", "run"], correct: 0 },
    { at: 299, tier: 2, q: "Will not let you go (_____ me go)", options: ["let", "make", "help", "watch"], correct: 0 },
    { at: 306, tier: 3, q: "Will not let you go (never, never, never, never let me _____)", options: ["go", "leave", "escape", "run"], correct: 0 },
    { at: 314, tier: 1, q: "No, no, no, no, no, no, _____", options: ["no", "yeah", "oh", "never"], correct: 0 },

    { at: 322, tier: 1, q: "Oh, mamma mia, mamma _____", options: ["mia", "me", "dear", "oh"], correct: 0 },
    { at: 329, tier: 1, q: "Mamma mia, let me _____", options: ["go", "leave", "out", "free"], correct: 0 },
    { at: 337, tier: 3, q: "Beelzebub has a devil put aside for _____, for me, for me", options: ["me", "you", "him", "us"], correct: 0 },
    { at: 346, tier: 3, q: "So you think you can stone me and spit in my _____?", options: ["eye", "face", "mouth", "hair"], correct: 0 },
    { at: 355, tier: 3, q: "So you think you can love me and leave me to _____?", options: ["die", "cry", "go", "fall"], correct: 0 },
    { at: 364, tier: 2, q: "Oh, baby, can't do this to me, _____", options: ["baby", "darling", "honey", "love"], correct: 0 },
    { at: 372, tier: 2, q: "Just gotta get _____, just gotta get right outta here", options: ["out", "away", "free", "back"], correct: 0 },

    { at: 383, tier: 1, q: "Ooh", options: ["Ooh", "Oh", "Ah", "Yeah"], correct: 0 },
    { at: 388, tier: 1, q: "Ooh, _____, ooh, yeah", options: ["yeah", "oh", "ah", "baby"], correct: 0 },
    { at: 394, tier: 2, q: "Nothing really _____, anyone can see", options: ["matters", "changes", "ends", "happens"], correct: 0 },
    { at: 402, tier: 1, q: "Nothing really _____", options: ["matters", "changes", "happens", "ends"], correct: 0 },
    { at: 409, tier: 1, q: "Nothing really matters to _____", options: ["me", "you", "us", "anyone"], correct: 0 }
  ]
},
   {
  id: "queen-another-one-bites-the-dust",
  questId: "Quest Video 27",
  category: "Queen",
  difficulty: "Intermediate",
  title: "Queen - Another One Bites the Dust (Lyrics)",
  youtubeId: "rY0WxgSXdEE",
  durationHint: 214,
  description: "Queen's iconic bass-driven hit 'Another One Bites the Dust'.",
  questions: [
    { at: 0,   tier: 1, q: "Ooh, let's _____", options: ["go", "move", "run", "dance"], correct: 0 },

    { at: 5,   tier: 1, q: "Steve walks warily down the _____", options: ["street", "road", "avenue", "lane"], correct: 0 },
    { at: 10,  tier: 2, q: "With the brim pulled way down _____", options: ["low", "far", "tight", "back"], correct: 0 },
    { at: 16,  tier: 2, q: "Ain't no sound but the sound of his _____", options: ["feet", "boots", "steps", "shoes"], correct: 0 },
    { at: 22,  tier: 2, q: "Machine guns ready to _____", options: ["go", "fire", "shoot", "roll"], correct: 0 },

    { at: 30,  tier: 1, q: "Are you ready? Hey, are you ready for _____?", options: ["this", "it", "me", "anything"], correct: 0 },
    { at: 36,  tier: 2, q: "Are you hanging on the edge of your _____?", options: ["seat", "chair", "bed", "world"], correct: 0 },
    { at: 43,  tier: 2, q: "Out of the doorway, the bullets _____", options: ["rip", "fly", "fire", "rain"], correct: 0 },
    { at: 49,  tier: 2, q: "To the sound of the _____, yeah", options: ["beat", "music", "drums", "gunfire"], correct: 0 },

    { at: 57,  tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 63,  tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 69,  tier: 2, q: "And another one gone, and another one _____", options: ["gone", "lost", "down", "dead"], correct: 0 },
    { at: 76,  tier: 1, q: "Another one bites the dust, _____", options: ["yeah", "hey", "oh", "now"], correct: 0 },
    { at: 82,  tier: 2, q: "Hey, I'm gonna get you _____", options: ["too", "now", "next", "soon"], correct: 0 },
    { at: 88,  tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },

    { at: 98,  tier: 2, q: "How do you think I'm going to get _____?", options: ["along", "through", "away", "back"], correct: 0 },
    { at: 104, tier: 2, q: "Without you, when you're _____", options: ["gone", "away", "dead", "leaving"], correct: 0 },
    { at: 111, tier: 2, q: "You took me for everything that I _____", options: ["had", "owned", "wanted", "needed"], correct: 0 },
    { at: 119, tier: 2, q: "And kicked me out on my _____", options: ["own", "feet", "way", "street"], correct: 0 },

    { at: 128, tier: 1, q: "Are you happy, are you _____?", options: ["satisfied", "content", "ready", "alright"], correct: 0 },
    { at: 135, tier: 2, q: "How long can you stand the _____?", options: ["heat", "pain", "pressure", "fire"], correct: 0 },
    { at: 142, tier: 2, q: "Out of the doorway the bullets _____", options: ["rip", "fly", "fire", "rain"], correct: 0 },
    { at: 149, tier: 2, q: "To the sound of the beat, look _____", options: ["out", "back", "down", "now"], correct: 0 },

    { at: 157, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 163, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 169, tier: 2, q: "And another one gone, and another one _____", options: ["gone", "lost", "down", "dead"], correct: 0 },
    { at: 176, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 182, tier: 2, q: "Hey, I'm gonna get you _____", options: ["too", "now", "next", "soon"], correct: 0 },
    { at: 188, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },

    { at: 197, tier: 1, q: "Hey! _____", options: ["Oh", "Yeah", "Hey", "Now"], correct: 0 },
    { at: 201, tier: 2, q: "Oh, take _____", options: ["it", "that", "this", "away"], correct: 0 },
    { at: 205, tier: 1, q: "Bite the _____", options: ["dust", "ground", "bullet", "floor"], correct: 0 },
    { at: 209, tier: 2, q: "Bite the dust, _____", options: ["hey", "yeah", "oh", "now"], correct: 0 },

    { at: 214, tier: 1, q: "Hey", options: ["Hey", "Yeah", "Oh", "Now"], correct: 0 },
    { at: 218, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 224, tier: 1, q: "Another one bites the dust, _____", options: ["oh", "hey", "yeah", "now"], correct: 0 },
    { at: 230, tier: 1, q: "Another one bites the dust, hey, _____", options: ["hey", "yeah", "oh", "now"], correct: 0 },
    { at: 236, tier: 1, q: "Another one bites the dust, _____", options: ["hey", "yeah", "oh", "now"], correct: 0 },
    { at: 242, tier: 2, q: "Ooh, shoot _____", options: ["out", "down", "now", "away"], correct: 0 },

    { at: 252, tier: 2, q: "There are plenty of ways that you can hurt a _____", options: ["man", "person", "boy", "guy"], correct: 0 },
    { at: 260, tier: 2, q: "And bring him to the _____", options: ["ground", "floor", "knees", "end"], correct: 0 },
    { at: 267, tier: 2, q: "You can beat him, you can cheat him, you can treat him _____", options: ["bad", "wrong", "poorly", "hard"], correct: 0 },
    { at: 276, tier: 2, q: "And leave him when he's _____, yeah", options: ["down", "gone", "hurt", "lost"], correct: 0 },

    { at: 286, tier: 2, q: "But I'm ready, yes, I'm ready for _____", options: ["you", "this", "it", "anything"], correct: 0 },
    { at: 293, tier: 2, q: "I'm standing on my own two _____", options: ["feet", "legs", "hands", "heels"], correct: 0 },
    { at: 300, tier: 2, q: "Out of the doorway the bullets _____", options: ["rip", "fly", "fire", "rain"], correct: 0 },
    { at: 307, tier: 3, q: "Repeating to the sound of the _____, oh, yeah", options: ["beat", "music", "drums", "sound"], correct: 0 },

    { at: 317, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 323, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },
    { at: 329, tier: 2, q: "And another one gone, and another one _____", options: ["gone", "lost", "down", "dead"], correct: 0 },
    { at: 336, tier: 1, q: "Another one bites the dust (_____)", options: ["yeah", "hey", "oh", "now"], correct: 0 },
    { at: 342, tier: 2, q: "Hey, I'm gonna get you _____", options: ["too", "now", "next", "soon"], correct: 0 },
    { at: 348, tier: 1, q: "Another one bites the _____", options: ["dust", "ground", "floor", "bullet"], correct: 0 },

    { at: 357, tier: 2, q: "Shoot _____", options: ["out", "down", "now", "away"], correct: 0 },
    { at: 362, tier: 1, q: "Yeah-_____", options: ["yeah", "yeah-oh", "oh", "hey"], correct: 0 },
    { at: 367, tier: 1, q: "_____", options: ["Alright", "Okay", "Come on", "Let's go"], correct: 0 }
  ]
},
   {
  id: "queen-killer-queen",
  questId: "Quest Video 32",
  category: "Queen",
  difficulty: "Advanced",
  title: "Queen - Killer Queen (Lyrics)",
  youtubeId: "2ZBtPf7FOoM",
  durationHint: 181,
  description: "Queen's sophisticated 1970s classic 'Killer Queen'.",
  questions: [
    { at: 0,   tier: 2, q: "She keeps the Moët & _____", options: ["Chandon", "Chandonne", "Champagne", "Cordon"], correct: 0 },
    { at: 5,   tier: 2, q: "In her pretty _____", options: ["cabinet", "closet", "bedroom", "boudoir"], correct: 0 },
    { at: 10,  tier: 2, q: "\"Let them eat _____,\" she says", options: ["cake", "caviar", "bread", "chocolate"], correct: 0 },
    { at: 16,  tier: 2, q: "Just like Marie _____", options: ["Antoinette", "Curie", "Therese", "Louise"], correct: 0 },
    { at: 23,  tier: 3, q: "A built-in remedy for Khrushchev and _____", options: ["Kennedy", "Nixon", "Johnson", "Truman"], correct: 0 },
    { at: 31,  tier: 3, q: "At any time, an invitation you can't _____", options: ["decline", "refuse", "reject", "avoid"], correct: 0 },

    { at: 41,  tier: 1, q: "Caviar and _____", options: ["cigarettes", "champagne", "chocolates", "cocktails"], correct: 0 },
    { at: 47,  tier: 2, q: "Well-versed in _____", options: ["etiquette", "manners", "fashion", "culture"], correct: 0 },
    { at: 53,  tier: 2, q: "Extraordinarily _____", options: ["nice", "beautiful", "charming", "elegant"], correct: 0 },

    { at: 62,  tier: 1, q: "She's a killer _____", options: ["queen", "woman", "lady", "girl"], correct: 0 },
    { at: 67,  tier: 2, q: "Gunpowder, _____", options: ["gelatine", "gasoline", "kerosene", "dynamite"], correct: 0 },
    { at: 72,  tier: 2, q: "Dynamite with a _____ beam", options: ["laser", "light", "blue", "silver"], correct: 0 },
    { at: 78,  tier: 3, q: "Guaranteed to blow your _____ (anytime)", options: ["mind", "head", "world", "doors"], correct: 0 },
    { at: 85,  tier: 2, q: "Ooh, recommended at the _____", options: ["price", "time", "place", "cost"], correct: 0 },
    { at: 91,  tier: 3, q: "Insatiable an _____", options: ["appetite", "ambition", "attitude", "attraction"], correct: 0 },
    { at: 97,  tier: 1, q: "Wanna _____?", options: ["try", "go", "know", "stay"], correct: 0 },

    { at: 106, tier: 2, q: "To avoid _____", options: ["complications", "problems", "questions", "trouble"], correct: 0 },
    { at: 112, tier: 2, q: "She never kept the same _____", options: ["address", "house", "number", "home"], correct: 0 },
    { at: 119, tier: 3, q: "In conversation, she spoke just like a _____", options: ["baroness", "princess", "duchess", "countess"], correct: 0 },
    { at: 127, tier: 2, q: "Met a man from _____", options: ["China", "Japan", "India", "Korea"], correct: 0 },
    { at: 134, tier: 3, q: "Went down to Geisha _____ (killer)", options: ["Minah", "Mina", "Mina-san", "Maria"], correct: 0 },
    { at: 141, tier: 3, q: "Then again incidentally (_____)", options: ["killer", "queen", "naturally", "anytime"], correct: 0 },
    { at: 147, tier: 3, q: "If you're that way inclined (she's a killer _____)", options: ["queen", "woman", "lady", "girl"], correct: 0 },

    { at: 157, tier: 2, q: "Perfume came naturally from _____ (naturally)", options: ["Paris", "London", "Rome", "Milan"], correct: 0 },
    { at: 164, tier: 2, q: "For cars, she couldn't care _____", options: ["less", "more", "at all", "enough"], correct: 0 },
    { at: 171, tier: 3, q: "Fastidious and _____", options: ["precise", "perfect", "particular", "proper"], correct: 0 },

    { at: 181, tier: 1, q: "She's a killer _____", options: ["queen", "woman", "lady", "girl"], correct: 0 },
    { at: 187, tier: 2, q: "Gunpowder, _____", options: ["gelatine", "gasoline", "kerosene", "dynamite"], correct: 0 },
    { at: 192, tier: 2, q: "Dynamite with a _____ beam", options: ["laser", "light", "blue", "silver"], correct: 0 },
    { at: 198, tier: 3, q: "Guaranteed to blow your _____ (anytime)", options: ["mind", "head", "world", "doors"], correct: 0 },

    { at: 207, tier: 2, q: "Drop of a _____, she's as willing as", options: ["hat", "coin", "pin", "stone"], correct: 0 },
    { at: 214, tier: 3, q: "Playful as a _____", options: ["pussycat", "kitten", "puppy", "fox"], correct: 0 },
    { at: 221, tier: 3, q: "Then momentarily out of _____", options: ["action", "sight", "time", "reach"], correct: 0 },
    { at: 228, tier: 3, q: "Temporarily out of _____", options: ["gas", "breath", "energy", "time"], correct: 0 },
    { at: 235, tier: 3, q: "To absolutely drive (drive you _____, wild)", options: ["wild", "crazy", "mad", "away"], correct: 0 },
    { at: 243, tier: 2, q: "She's out to get _____", options: ["you", "him", "them", "me"], correct: 0 },

    { at: 253, tier: 1, q: "She's a killer _____", options: ["queen", "woman", "lady", "girl"], correct: 0 },
    { at: 259, tier: 2, q: "Gunpowder, _____", options: ["gelatine", "gasoline", "kerosene", "dynamite"], correct: 0 },
    { at: 264, tier: 2, q: "Dynamite with a _____ beam", options: ["laser", "light", "blue", "silver"], correct: 0 },
    { at: 270, tier: 3, q: "Guaranteed to blow your _____ (anytime)", options: ["mind", "head", "world", "doors"], correct: 0 },
    { at: 277, tier: 2, q: "Ooh, recommended at the _____", options: ["price", "time", "place", "cost"], correct: 0 },
    { at: 283, tier: 3, q: "Insatiable an _____ (wanna try?)", options: ["appetite", "ambition", "attitude", "attraction"], correct: 0 },
    { at: 290, tier: 1, q: "You wanna _____?", options: ["try", "go", "know", "stay"], correct: 0 }
  ]
},
   {
  id: "queen-crazy-little-thing-called-love",
  questId: "Quest Video 36",
  category: "Queen",
  difficulty: "Intermediate",
  title: "Queen - Crazy Little Thing Called Love (Lyrics)",
  youtubeId: "zO6D_BAuYCI",
  durationHint: 163,
  description: "Queen's rockabilly-inspired hit 'Crazy Little Thing Called Love'.",
  questions: [
    { at: 0,   tier: 1, q: "This thing called _____", options: ["love", "life", "music", "freedom"], correct: 0 },
    { at: 5,   tier: 1, q: "I just can't _____ it", options: ["handle", "take", "stand", "face"], correct: 0 },
    { at: 10,  tier: 1, q: "This thing called _____", options: ["love", "life", "music", "freedom"], correct: 0 },
    { at: 15,  tier: 2, q: "I must get _____ to it", options: ["'round", "back", "used", "close"], correct: 0 },
    { at: 21,  tier: 1, q: "I ain't _____", options: ["ready", "sure", "able", "prepared"], correct: 0 },
    { at: 26,  tier: 2, q: "Crazy little thing called _____", options: ["love", "life", "music", "you"], correct: 0 },

    { at: 34,  tier: 2, q: "This thing (this thing) called _____ (called love)", options: ["love", "life", "music", "freedom"], correct: 0 },
    { at: 42,  tier: 2, q: "It cries (like a _____), in a cradle all night", options: ["baby", "child", "kitten", "bird"], correct: 0 },
    { at: 51,  tier: 2, q: "It swings (woo), it _____ (woo)", options: ["jives", "dances", "rocks", "moves"], correct: 0 },
    { at: 58,  tier: 3, q: "Shakes all over like a _____", options: ["jellyfish", "fish", "wave", "marionette"], correct: 0 },
    { at: 67,  tier: 2, q: "I kinda _____ it", options: ["like", "love", "want", "need"], correct: 0 },
    { at: 73,  tier: 2, q: "Crazy little thing called _____", options: ["love", "life", "music", "you"], correct: 0 },

    { at: 83,  tier: 1, q: "There goes my _____", options: ["baby", "lady", "girl", "lover"], correct: 0 },
    { at: 89,  tier: 2, q: "She knows how to rock and _____", options: ["roll", "dance", "move", "swing"], correct: 0 },
    { at: 96,  tier: 2, q: "She drives me _____", options: ["crazy", "wild", "mad", "away"], correct: 0 },
    { at: 103, tier: 3, q: "She gives me hot and cold _____", options: ["fever", "sweat", "shivers", "feelings"], correct: 0 },
    { at: 110, tier: 3, q: "She leaves me in a cool, cool _____", options: ["sweat", "breeze", "room", "night"], correct: 0 },

    { at: 120, tier: 1, q: "I gotta be _____, relax", options: ["cool", "calm", "ready", "strong"], correct: 0 },
    { at: 125, tier: 2, q: "Get hip and get on my _____", options: ["tracks", "feet", "bike", "way"], correct: 0 },
    { at: 131, tier: 2, q: "Take a back seat, _____", options: ["hitchhike", "drive", "relax", "wait"], correct: 0 },
    { at: 138, tier: 3, q: "And take a long ride on my _____", options: ["motorbike", "motorcycle", "car", "bicycle"], correct: 0 },
    { at: 146, tier: 2, q: "Until I'm _____", options: ["ready", "cool", "free", "there"], correct: 0 },
    { at: 151, tier: 2, q: "Crazy little thing called _____", options: ["love", "life", "music", "you"], correct: 0 },

    { at: 160, tier: 1, q: "Yeah", options: ["Yeah", "Hey", "Oh", "Ooh"], correct: 0 },

    { at: 166, tier: 1, q: "I gotta be _____, relax", options: ["cool", "calm", "ready", "strong"], correct: 0 },
    { at: 171, tier: 2, q: "Get hip and get on my _____", options: ["tracks", "feet", "bike", "way"], correct: 0 },
    { at: 177, tier: 2, q: "Take a back seat, _____", options: ["hitchhike", "drive", "relax", "wait"], correct: 0 },
    { at: 184, tier: 3, q: "And take a long ride on my _____", options: ["motorbike", "motorcycle", "car", "bicycle"], correct: 0 },
    { at: 192, tier: 2, q: "Until I'm ready (ready _____)", options: ["Freddie", "baby", "now", "again"], correct: 0 },
    { at: 198, tier: 2, q: "Crazy little thing called _____", options: ["love", "life", "music", "you"], correct: 0 },

    { at: 208, tier: 1, q: "This thing called _____", options: ["love", "life", "music", "freedom"], correct: 0 },
    { at: 213, tier: 1, q: "I just can't _____ it", options: ["handle", "take", "stand", "face"], correct: 0 },
    { at: 218, tier: 1, q: "This thing called _____", options: ["love", "life", "music", "freedom"], correct: 0 },
    { at: 223, tier: 2, q: "I must get _____ to it", options: ["'round", "back", "used", "close"], correct: 0 },
    { at: 229, tier: 1, q: "I ain't _____", options: ["ready", "sure", "able", "prepared"], correct: 0 },
    { at: 234, tier: 2, q: "Crazy little thing called _____", options: ["love", "life", "music", "you"], correct: 0 },

  ]
},
   {
  id: "queen-we-are-the-champions",
  questId: "Quest Video 34",
  category: "Queen",
  difficulty: "Intermediate",
  title: "Queen - We Are the Champions (Lyrics)",
  youtubeId: "04854XqcfCY",
  durationHint: 189,
  description: "A lyric video for Queen's triumphant anthem 'We Are the Champions'.",
  questions: [
    { at: 0,   tier: 1, q: "I've paid my _____", options: ["dues", "debts", "price", "share"], correct: 0 },
    { at: 5,   tier: 1, q: "Time after _____", options: ["time", "time again", "night", "day"], correct: 0 },
    { at: 10,  tier: 1, q: "I've done my _____", options: ["sentence", "duty", "time", "part"], correct: 0 },
    { at: 15,  tier: 2, q: "But committed no _____", options: ["crime", "wrong", "sin", "mistake"], correct: 0 },

    { at: 22,  tier: 1, q: "And bad _____", options: ["mistakes", "decisions", "choices", "memories"], correct: 0 },
    { at: 27,  tier: 1, q: "I've made a _____", options: ["few", "lot", "mistake", "choice"], correct: 0 },
    { at: 32,  tier: 2, q: "I've had my share of sand kicked in my _____", options: ["face", "eyes", "teeth", "hair"], correct: 0 },
    { at: 40,  tier: 2, q: "But I've come _____", options: ["through", "back", "out", "far"], correct: 0 },
    { at: 48,  tier: 3, q: "And I mean to go on, and on, and on, and _____", options: ["on", "up", "forward", "again"], correct: 0 },

    { at: 57,  tier: 1, q: "We are the _____, my friends", options: ["champions", "winners", "victors", "fighters"], correct: 0 },
    { at: 64,  tier: 2, q: "And we'll keep on fighting 'til the _____", options: ["end", "finish", "start", "top"], correct: 0 },
    { at: 72,  tier: 1, q: "We are the _____", options: ["champions", "winners", "heroes", "victors"], correct: 0 },
    { at: 78,  tier: 1, q: "We are the _____", options: ["champions", "fighters", "winners", "leaders"], correct: 0 },
    { at: 84,  tier: 2, q: "No time for _____", options: ["losers", "quitters", "failures", "doubters"], correct: 0 },
    { at: 91,  tier: 1, q: "'Cause we are the _____", options: ["champions", "winners", "leaders", "heroes"], correct: 0 },
    { at: 98,  tier: 2, q: "Of the _____", options: ["world", "game", "nation", "championship"], correct: 0 },

    { at: 108, tier: 2, q: "I've taken my _____", options: ["bows", "awards", "prizes", "honours"], correct: 0 },
    { at: 115, tier: 2, q: "And my curtain _____", options: ["calls", "falls", "rises", "drops"], correct: 0 },
    { at: 122, tier: 2, q: "You brought me fame and _____", options: ["fortune", "success", "glory", "wealth"], correct: 0 },
    { at: 130, tier: 3, q: "And everything that goes with _____", options: ["it", "that", "this", "them"], correct: 0 },
    { at: 137, tier: 1, q: "I thank you _____", options: ["all", "both", "dearly", "again"], correct: 0 },

    { at: 145, tier: 2, q: "But it's been no bed of _____", options: ["roses", "flowers", "dreams", "leaves"], correct: 0 },
    { at: 151, tier: 2, q: "No pleasure _____", options: ["cruise", "ride", "trip", "journey"], correct: 0 },
    { at: 158, tier: 3, q: "I consider it a challenge before the whole human _____", options: ["race", "world", "kind", "species"], correct: 0 },
    { at: 167, tier: 2, q: "And I ain't gonna _____", options: ["lose", "quit", "fall", "stop"], correct: 0 },
    { at: 174, tier: 3, q: "And I mean to go on, and on, and on, and _____", options: ["on", "up", "forward", "again"], correct: 0 },

    { at: 183, tier: 1, q: "We are the _____, my friends", options: ["champions", "winners", "victors", "fighters"], correct: 0 },
    { at: 190, tier: 2, q: "And we'll keep on fighting 'til the _____", options: ["end", "finish", "start", "top"], correct: 0 },
    { at: 198, tier: 1, q: "We are the _____", options: ["champions", "winners", "heroes", "victors"], correct: 0 },
    { at: 204, tier: 1, q: "We are the _____", options: ["champions", "fighters", "winners", "leaders"], correct: 0 },
    { at: 210, tier: 2, q: "No time for _____", options: ["losers", "quitters", "failures", "doubters"], correct: 0 },
    { at: 216, tier: 1, q: "'Cause we are the _____", options: ["champions", "winners", "leaders", "heroes"], correct: 0 },
    { at: 223, tier: 2, q: "Of the _____", options: ["world", "game", "nation", "championship"], correct: 0 },

    { at: 232, tier: 1, q: "We are the _____, my friends", options: ["champions", "winners", "victors", "fighters"], correct: 0 },
    { at: 239, tier: 2, q: "And we'll keep on fighting 'til the _____, oh", options: ["end", "finish", "start", "top"], correct: 0 },
    { at: 247, tier: 1, q: "We are the _____", options: ["champions", "winners", "heroes", "victors"], correct: 0 },
    { at: 253, tier: 1, q: "We are the _____", options: ["champions", "fighters", "winners", "leaders"], correct: 0 },
    { at: 259, tier: 2, q: "No time for _____", options: ["losers", "quitters", "failures", "doubters"], correct: 0 },
    { at: 266, tier: 1, q: "'Cause we are the _____", options: ["champions", "winners", "leaders", "heroes"], correct: 0 }
  ]
},
   {
  id: "queen-dont-stop-me-now",
  questId: "Quest Video 26",
  category: "Queen",
  difficulty: "Intermediate",
  title: "Queen - Don't Stop Me Now (Lyrics)",
  youtubeId: "HgzGwKwLmgM",
  durationHint: 209,
  description: "A lyric video for Queen's exuberant classic 'Don't Stop Me Now'.",
  questions: [
    { at: 0,   tier: 1, q: "Tonight, I'm gonna have _____", options: ["myself", "a ball", "a good time", "fun"], correct: 0 },
    { at: 4,   tier: 1, q: "A real _____ time, I feel alive", options: ["good", "great", "wonderful", "fine"], correct: 0 },
    { at: 8,   tier: 2, q: "And the world, I'll turn it _____ out, yeah", options: ["inside", "upside", "around", "inside and"], correct: 0 },
    { at: 13,  tier: 2, q: "I'm floating around in _____, so", options: ["ecstasy", "happiness", "heaven", "space"], correct: 0 },

    { at: 20,  tier: 1, q: "Don't stop me _____", options: ["now", "tonight", "here", "ever"], correct: 0 },
    { at: 24,  tier: 1, q: "Don't stop _____", options: ["me", "now", "this", "it"], correct: 0 },
    { at: 28,  tier: 1, q: "'Cause I'm having a good time, having a _____ time", options: ["good", "great", "wonderful", "fine"], correct: 0 },

    { at: 38,  tier: 2, q: "I'm a shooting _____ leaping through the sky like a tiger", options: ["star", "rocket", "comet", "arrow"], correct: 0 },
    { at: 45,  tier: 3, q: "Defying the laws of _____", options: ["gravity", "physics", "nature", "motion"], correct: 0 },
    { at: 52,  tier: 2, q: "I'm a racing car, passing by like Lady _____", options: ["Godiva", "Diana", "Jane", "Mary"], correct: 0 },
    { at: 60,  tier: 2, q: "I'm gonna go, go, go, there's no _____ me", options: ["stopping", "catching", "holding", "slowing"], correct: 0 },

    { at: 69,  tier: 1, q: "I'm burnin' through the _____, yeah", options: ["sky", "night", "air", "clouds"], correct: 0 },
    { at: 74,  tier: 2, q: "200 degrees, that's why they call me Mister _____", options: ["Fahrenheit", "Celsius", "Mercury", "Heat"], correct: 0 },
    { at: 82,  tier: 2, q: "I'm travelling at the speed of _____", options: ["light", "sound", "time", "energy"], correct: 0 },
    { at: 89,  tier: 3, q: "I wanna make a supersonic _____ out of you", options: ["man", "woman", "person", "hero"], correct: 0 },

    { at: 99,  tier: 1, q: "I'm having such a _____ time", options: ["good", "great", "fine", "wonderful"], correct: 0 },
    { at: 104, tier: 1, q: "I'm having a _____", options: ["ball", "blast", "party", "laugh"], correct: 0 },
    { at: 111, tier: 2, q: "(Don't stop me now) if you wanna have a _____ time", options: ["good", "great", "wild", "wonderful"], correct: 0 },
    { at: 119, tier: 1, q: "Just give me a _____", options: ["call", "sign", "ring", "chance"], correct: 0 },

    { at: 128, tier: 1, q: "'Cause I'm having a _____ time", options: ["good", "great", "wonderful", "fine"], correct: 0 },
    { at: 135, tier: 1, q: "(Don't stop me now) yes, I'm havin' a _____ time", options: ["good", "great", "wonderful", "fine"], correct: 0 },
    { at: 142, tier: 2, q: "I don't wanna stop at _____, yeah", options: ["all", "all now", "once", "anytime"], correct: 0 },

    { at: 151, tier: 2, q: "I'm a rocket ship on my way to _____ on a collision course", options: ["Mars", "Venus", "Jupiter", "Earth"], correct: 0 },
    { at: 159, tier: 2, q: "I am a satellite, I'm out of _____", options: ["control", "orbit", "time", "space"], correct: 0 },
    { at: 167, tier: 3, q: "I'm a sex machine ready to reload like an _____ bomb", options: ["atom", "atomic", "H-bomb", "energy"], correct: 0 },
    { at: 175, tier: 3, q: "About to whoa-oh, whoa-oh, oh, _____", options: ["explode", "collide", "ignite", "erupt"], correct: 0 },

    { at: 183, tier: 1, q: "I'm burnin' through the _____, yeah", options: ["sky", "night", "air", "clouds"], correct: 0 },
    { at: 188, tier: 2, q: "200 degrees, that's why they call me Mister _____, hey", options: ["Fahrenheit", "Celsius", "Mercury", "Heat"], correct: 0 },
    { at: 196, tier: 2, q: "I'm travelling at the speed of _____", options: ["light", "sound", "time", "energy"], correct: 0 },
    { at: 203, tier: 3, q: "I wanna make a supersonic _____ of you", options: ["woman", "man", "person", "hero"], correct: 0 },

    { at: 213, tier: 1, q: "hey-hey-hey", options: ["hey-hey-hey", "yeah-yeah-yeah", "oh-oh-oh", "la-la-la"], correct: 0 },
    { at: 218, tier: 2, q: "(Don't stop me, don't stop me, ooh-ooh-ooh) I _____ it", options: ["like", "love", "want", "need"], correct: 0 },
    { at: 224, tier: 1, q: "(Don't stop me, don't stop me) have a _____ time, good time", options: ["good", "great", "wild", "real"], correct: 0 },
    { at: 231, tier: 1, q: "(Don't stop me, don't stop me) _____", options: ["oh", "yeah", "hey", "now"], correct: 0 },
    { at: 236, tier: 2, q: "Let loose, _____, alright", options: ["honey", "baby", "darling", "woman"], correct: 0 },

    { at: 243, tier: 1, q: "Oh, I'm burnin' through the _____, yeah", options: ["sky", "night", "air", "clouds"], correct: 0 },
    { at: 248, tier: 2, q: "200 degrees, that's why they call me Mister Fahrenheit, _____", options: ["hey", "yeah", "oh", "now"], correct: 0 },
    { at: 256, tier: 2, q: "I'm travelling at the speed of _____", options: ["light", "sound", "time", "energy"], correct: 0 },
    { at: 263, tier: 3, q: "I wanna make a supersonic man out of you (hey, _____)", options: ["hey", "yeah", "now", "oh"], correct: 0 },

    { at: 273, tier: 1, q: "I'm having such a _____ time", options: ["good", "great", "wonderful", "fine"], correct: 0 },
    { at: 278, tier: 1, q: "I'm having a _____", options: ["ball", "blast", "party", "laugh"], correct: 0 },
    { at: 285, tier: 2, q: "(Don't stop me now) if you wanna have a good time (ooh, _____)", options: ["alright", "okay", "yeah", "come on"], correct: 0 },
    { at: 293, tier: 1, q: "Just give me a _____", options: ["call", "ring", "sign", "chance"], correct: 0 },

    { at: 302, tier: 1, q: "yes, I'm havin' a _____ time", options: ["good", "great", "wonderful", "fine"], correct: 0 },
    { at: 309, tier: 2, q: "I don't wanna stop at _____", options: ["all", "all now", "once", "anytime"], correct: 0 },

    { at: 317, tier: 1, q: "Ah, da-da-da-da- da-da-_____", options: ["ah-ah", "oh-oh", "yeah-yeah", "la-la"], correct: 0 },
    { at: 322, tier: 1, q: "Ah-da-da, _____", options: ["ah-ah-ah", "oh-oh-oh", "yeah-yeah", "la-la-la"], correct: 0 },
    { at: 327, tier: 2, q: "Ah, da-da, da-da-da-da-_____", options: ["ah-ah", "oh-oh", "yeah-yeah", "la-la"], correct: 0 },
    { at: 333, tier: 1, q: "Ooh, ooh-ooh, ooh-_____", options: ["ooh", "ah", "yeah", "oh"], correct: 0 }
  ]
},
   {
  id: "queen-who-wants-to-live-forever",
  questId: "Quest Video 35",
  category: "Queen",
  difficulty: "Intermediate",
  title: "Queen - Who Wants to Live Forever (Lyrics)",
  youtubeId: "_Jtpf8N5IDE",
  durationHint: 240,
  description: "Queen's haunting classic 'Who Wants to Live Forever' from A Kind of Magic.",
  questions: [
    { at: 0,   tier: 1, q: "There's no _____ for us", options: ["time", "place", "chance", "hope"], correct: 0 },
    { at: 7,   tier: 1, q: "There's no _____ for us", options: ["place", "time", "chance", "reason"], correct: 0 },
    { at: 14,  tier: 2, q: "What is this thing that builds our _____", options: ["dreams", "hopes", "lives", "future"], correct: 0 },
    { at: 22,  tier: 2, q: "Yet slips _____ from us", options: ["away", "out", "down", "by"], correct: 0 },

    { at: 31,  tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "alone", "always"], correct: 0 },
    { at: 38,  tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "always", "alone"], correct: 0 },
    { at: 45,  tier: 1, q: "Oh _____ oh", options: ["ooo", "oooh", "ah", "yeah"], correct: 0 },

    { at: 55,  tier: 1, q: "There's no _____ for us", options: ["chance", "hope", "time", "place"], correct: 0 },
    { at: 63,  tier: 2, q: "It's all _____ for us", options: ["decided", "planned", "written", "chosen"], correct: 0 },
    { at: 72,  tier: 3, q: "This world has only one sweet _____ set aside for us", options: ["moment", "chance", "day", "dream"], correct: 0 },

    { at: 84,  tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "always", "alone"], correct: 0 },
    { at: 92,  tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "always", "alone"], correct: 0 },
    { at: 100, tier: 1, q: "_____", options: ["Ooh", "Oh", "Ah", "Yeah"], correct: 0 },

    { at: 109, tier: 3, q: "Who dares to love _____?", options: ["forever", "again", "always", "someone"], correct: 0 },
    { at: 118, tier: 2, q: "Oh oo woh, when love must _____", options: ["die", "end", "fade", "go"], correct: 0 },

    { at: 129, tier: 2, q: "But touch my _____ with your lips", options: ["tears", "heart", "face", "eyes"], correct: 0 },
    { at: 138, tier: 2, q: "Touch my _____ with your fingertips", options: ["world", "heart", "face", "soul"], correct: 0 },
    { at: 148, tier: 2, q: "And we can have _____", options: ["forever", "everything", "tomorrow", "love"], correct: 0 },
    { at: 157, tier: 2, q: "And we can love _____", options: ["forever", "again", "always", "together"], correct: 0 },
    { at: 166, tier: 2, q: "Forever is our _____", options: ["today", "tomorrow", "moment", "dream"], correct: 0 },

    { at: 178, tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "always", "alone"], correct: 0 },
    { at: 186, tier: 1, q: "Who wants to live _____?", options: ["forever", "again", "always", "alone"], correct: 0 },
    { at: 195, tier: 2, q: "Forever is our _____", options: ["today", "tomorrow", "moment", "dream"], correct: 0 },
    { at: 205, tier: 3, q: "Who waits _____ anyway?", options: ["forever", "alone", "there", "again"], correct: 0 }
  ]
},
   {
  id: "vast-the-show-must-go-on", questId: "Quest Video 24", category: "Queen", difficulty: "Intermediate",
  title: "Queen - The Show Must Go On (Lyrics)", youtubeId: "uKLMYZlbIb8", durationHint: 230,
  description: "A lyric video by Vast for Queen's powerful anthem 'The Show Must Go On'.",
  questions: [
    { at: 0,   tier: 1, q: "What are we living _____?", options: ["for", "with", "on", "through"], correct: 0 },
    { at: 7,   tier: 1, q: "_____ places", options: ["Empty", "Abandoned", "Forgotten", "Broken"], correct: 1 },
    { at: 14,  tier: 2, q: "I guess we know the _____", options: ["answer", "score", "reason", "truth"], correct: 1 },
    { at: 22,  tier: 2, q: "Does anybody know what we are _____ for?", options: ["waiting", "looking", "living", "fighting"], correct: 1 },
    { at: 31,  tier: 1, q: "Another _____, another mindless crime.", options: ["villain", "hero", "soldier", "leader"], correct: 1 },
    { at: 39,  tier: 2, q: "Behind the _____", options: ["stage", "curtain", "door", "scenes"], correct: 1 },
    { at: 47,  tier: 2, q: "In the _____", options: ["pantomime", "theatre", "playhouse", "drama"], correct: 0 },
    { at: 55,  tier: 3, q: "Does anybody want to take it _____?", options: ["again", "anymore", "further", "away"], correct: 1 },
    { at: 65,  tier: 1, q: "The show must _____", options: ["begin", "continue", "go on", "end"], correct: 2 },
    { at: 74,  tier: 2, q: "Inside my heart is _____", options: ["breaking", "crying", "aching", "falling"], correct: 0 },
    { at: 82,  tier: 2, q: "My make-up may be _____", options: ["fading", "falling", "flaking", "running"], correct: 2 },
    { at: 90,  tier: 1, q: "But my smile still stays _____", options: ["strong", "on", "bright", "there"], correct: 1 },
    { at: 101, tier: 2, q: "Whatever happens, I'll leave it all to _____", options: ["fate", "chance", "destiny", "time"], correct: 1 },
    { at: 110, tier: 2, q: "Another heartache, another failed _____", options: ["dream", "relationship", "romance", "attempt"], correct: 2 },
    { at: 124, tier: 1, q: "I must be _____ now", options: ["stronger", "warmer", "wiser", "braver"], correct: 1 },
    { at: 135, tier: 2, q: "I'll soon be turning _____ the corner now", options: ["around", "round", "past", "toward"], correct: 1 },
    { at: 145, tier: 3, q: "Outside the dawn is _____", options: ["rising", "breaking", "coming", "shining"], correct: 1 },
    { at: 154, tier: 3, q: "Inside in the dark I'm aching to be _____", options: ["heard", "free", "strong", "alive"], correct: 1 },
    { at: 169, tier: 3, q: "My soul is painted like the wings of _____", options: ["birds", "angels", "butterflies", "fairies"], correct: 2 },
    { at: 181, tier: 3, q: "Fairy tales of yesterday will grow but never _____", options: ["fade", "end", "die", "change"], correct: 2 },
    { at: 190, tier: 2, q: "I can fly, my _____", options: ["friends", "people", "brothers", "lovers"], correct: 0 },
    { at: 202, tier: 2, q: "I'll face it with a _____", options: ["smile", "grin", "laugh", "fight"], correct: 1 },
    { at: 210, tier: 1, q: "I'm never giving _____", options: ["up", "in", "out", "away"], correct: 1 },
    { at: 217, tier: 2, q: "I'll top the _____", options: ["stage", "bill", "show", "list"], correct: 1 },
    { at: 224, tier: 3, q: "I have to find the _____ to carry on with the show.", options: ["strength", "courage", "will", "power"], correct: 2 }
  ]
},
   {
  id: "abba-thank-you-for-the-music",
  questId: "Quest Video 37",
  category: "ABBA",
  difficulty: "Intermediate",
  title: "ABBA - Thank You for the Music (Lyrics)",
  youtubeId: "XEjLoHdbVeE",
  durationHint: 214,
  description: "ABBA's beloved celebration of music, singing, and the joy they bring.",
  questions: [
    { at: 0,   tier: 2, q: "I'm nothing special, in fact I'm a bit of a _____", options: ["bore", "fool", "dreamer", "loser"], correct: 0 },
    { at: 7,   tier: 2, q: "If I tell a joke, you've probably heard it _____", options: ["before", "already", "once", "somewhere"], correct: 0 },
    { at: 14,  tier: 2, q: "But I have a _____, a wonderful thing", options: ["talent", "voice", "gift", "dream"], correct: 0 },
    { at: 21,  tier: 2, q: "'Cause everyone listens when I start to _____", options: ["sing", "speak", "dance", "play"], correct: 0 },
    { at: 28,  tier: 1, q: "I'm so grateful and _____", options: ["proud", "happy", "thankful", "lucky"], correct: 0 },
    { at: 34,  tier: 2, q: "All I want is to sing it out _____", options: ["loud", "clear", "strong", "proud"], correct: 0 },

    { at: 44,  tier: 1, q: "So I say thank you for the _____, the songs I'm singing", options: ["music", "songs", "sound", "joy"], correct: 0 },
    { at: 52,  tier: 2, q: "Thanks for all the _____ they're bringing", options: ["joy", "love", "happiness", "memories"], correct: 0 },
    { at: 60,  tier: 3, q: "Who can live without it? I ask in all _____", options: ["honesty", "earnest", "seriousness", "truth"], correct: 0 },
    { at: 67,  tier: 2, q: "What would life _____?", options: ["be", "mean", "bring", "become"], correct: 0 },
    { at: 73,  tier: 3, q: "Without a song or a dance, what are _____?", options: ["we", "they", "you", "I"], correct: 0 },
    { at: 81,  tier: 2, q: "So I say thank you for the music, for giving it to _____", options: ["me", "us", "you", "all"], correct: 0 },

    { at: 94,  tier: 2, q: "Mother says I was a dancer before I could _____", options: ["walk", "talk", "sing", "stand"], correct: 0 },
    { at: 101, tier: 1, q: "Mhm, she says I began to sing long before I could _____", options: ["talk", "walk", "dance", "run"], correct: 0 },
    { at: 109, tier: 2, q: "And I've often wondered, how did it all _____?", options: ["start", "begin", "happen", "come"], correct: 0 },
    { at: 117, tier: 3, q: "Who found out that nothing can capture a _____", options: ["heart", "mind", "soul", "dream"], correct: 0 },
    { at: 124, tier: 3, q: "Like a _____ can?", options: ["melody", "song", "voice", "dance"], correct: 0 },
    { at: 131, tier: 2, q: "Well, whoever it was, I'm a _____", options: ["fan", "believer", "friend", "fanatic"], correct: 0 },

    { at: 142, tier: 1, q: "So I say thank you for the _____, the songs I'm singing", options: ["music", "songs", "sound", "joy"], correct: 0 },
    { at: 150, tier: 2, q: "Thanks for all the _____ they're bringing", options: ["joy", "love", "happiness", "memories"], correct: 0 },
    { at: 158, tier: 3, q: "Who can live without it? I ask in all _____", options: ["honesty", "earnest", "seriousness", "truth"], correct: 0 },
    { at: 165, tier: 2, q: "What would life _____?", options: ["be", "mean", "bring", "become"], correct: 0 },
    { at: 171, tier: 3, q: "Without a song or a dance, what are _____?", options: ["we", "they", "you", "I"], correct: 0 },
    { at: 179, tier: 2, q: "So I say thank you for the music, for giving it to _____", options: ["me", "us", "you", "all"], correct: 0 },

    { at: 192, tier: 2, q: "I've been so _____", options: ["lucky", "happy", "grateful", "proud"], correct: 0 },
    { at: 198, tier: 2, q: "I am the girl with golden _____", options: ["hair", "eyes", "voice", "shoes"], correct: 0 },
    { at: 205, tier: 2, q: "I wanna sing it out to _____", options: ["everybody", "everyone", "the world", "you"], correct: 0 },
    { at: 212, tier: 2, q: "What a joy, what a life, what a _____", options: ["chance", "dream", "gift", "thing"], correct: 0 },

    { at: 223, tier: 1, q: "Thank you for the _____, the songs I'm singing", options: ["music", "songs", "sound", "joy"], correct: 0 },
    { at: 231, tier: 2, q: "Thanks for all the _____ they're bringing", options: ["joy", "love", "happiness", "memories"], correct: 0 },
    { at: 239, tier: 3, q: "Who can live without it? I ask in all _____", options: ["honesty", "earnest", "seriousness", "truth"], correct: 0 },
    { at: 246, tier: 2, q: "What would life _____?", options: ["be", "mean", "bring", "become"], correct: 0 },
    { at: 252, tier: 3, q: "Without a song or a dance, what are _____?", options: ["we", "they", "you", "I"], correct: 0 },
    { at: 260, tier: 2, q: "So I say thank you for the music, for giving it to _____", options: ["me", "us", "you", "all"], correct: 0 },

    { at: 274, tier: 2, q: "So I say thank you for the music, for giving it to _____", options: ["me", "us", "you", "all"], correct: 0 }
  ]
},
   {
  id: "abba-eagle",
  questId: "Quest Video 38",
  category: "ABBA",
  difficulty: "Intermediate",
  title: "ABBA - Eagle (Lyrics)",
  youtubeId: "dDIJMMd4m2E",
  durationHint: 274,
  description: "ABBA's soaring anthem 'Eagle', inspired by the freedom of flight and boundless imagination.",
  questions: [
    { at: 0,   tier: 2, q: "They came flyin' from far away, now I'm under their _____", options: ["spell", "control", "wings", "power"], correct: 0 },
    { at: 8,   tier: 2, q: "I love hearing the stories that they _____", options: ["tell", "know", "bring", "share"], correct: 0 },
    { at: 16,  tier: 2, q: "They've seen places beyond my _____ and they've found new horizons", options: ["land", "home", "world", "country"], correct: 0 },
    { at: 25,  tier: 2, q: "They speak strangely but I _____", options: ["understand", "listen", "know", "agree"], correct: 0 },

    { at: 35,  tier: 1, q: "And I dream I'm an _____", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 42,  tier: 2, q: "And I dream I can spread my _____", options: ["wings", "arms", "hands", "feathers"], correct: 0 },
    { at: 50,  tier: 1, q: "Flyin' high, high, I'm a bird in the _____", options: ["sky", "air", "clouds", "wind"], correct: 0 },
    { at: 58,  tier: 2, q: "I'm an eagle that rides on the _____", options: ["breeze", "wind", "air", "cloud"], correct: 0 },
    { at: 66,  tier: 1, q: "High, high, what a feeling to _____", options: ["fly", "soar", "rise", "float"], correct: 0 },
    { at: 74,  tier: 2, q: "Over mountains and forests and _____", options: ["seas", "rivers", "valleys", "lakes"], correct: 0 },
    { at: 83,  tier: 2, q: "And to go anywhere that I _____", options: ["please", "want", "choose", "can"], correct: 0 },

    { at: 96,  tier: 2, q: "As all good friends we talk all night, and we fly wing to _____", options: ["wing", "wing", "wing", "wing"], correct: 0 },
    { at: 104, tier: 2, q: "I have questions and they know _____", options: ["everything", "nothing", "enough", "more"], correct: 0 },
    { at: 113, tier: 2, q: "There's no limit to what I feel, we climb higher and _____", options: ["higher", "further", "faster", "farther"], correct: 0 },
    { at: 122, tier: 3, q: "Am I dreamin' or is it all _____", options: ["real", "true", "possible", "there"], correct: 0 },

    { at: 135, tier: 2, q: "Is it true I'm an _____", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 143, tier: 2, q: "Is it true I can spread my _____", options: ["wings", "arms", "hands", "feathers"], correct: 0 },
    { at: 151, tier: 1, q: "Flying high, high, I'm a bird in the _____", options: ["sky", "air", "clouds", "wind"], correct: 0 },
    { at: 159, tier: 2, q: "(I'm an _____)", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 166, tier: 2, q: "I'm an eagle that rides on the _____", options: ["breeze", "wind", "air", "cloud"], correct: 0 },
    { at: 174, tier: 1, q: "High, high, what a feeling to _____", options: ["fly", "soar", "rise", "float"], correct: 0 },
    { at: 181, tier: 2, q: "(What a _____)", options: ["feeling", "dream", "sight", "joy"], correct: 0 },
    { at: 188, tier: 2, q: "Over mountains and forests and _____", options: ["seas", "rivers", "valleys", "lakes"], correct: 0 },
    { at: 196, tier: 2, q: "And to go anywhere that I _____", options: ["please", "want", "choose", "can"], correct: 0 },

    { at: 210, tier: 2, q: "And I dream I'm an _____", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 218, tier: 2, q: "And I dream I can spread my _____", options: ["wings", "arms", "hands", "feathers"], correct: 0 },
    { at: 226, tier: 1, q: "Flying high, high, I'm a bird in the _____", options: ["sky", "air", "clouds", "wind"], correct: 0 },
    { at: 234, tier: 2, q: "(I'm an _____)", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 241, tier: 2, q: "I'm an eagle that rides on the _____", options: ["breeze", "wind", "air", "cloud"], correct: 0 },
    { at: 249, tier: 1, q: "High, high, what a feeling to _____", options: ["fly", "soar", "rise", "float"], correct: 0 },
    { at: 256, tier: 2, q: "(What a _____)", options: ["feeling", "dream", "sight", "joy"], correct: 0 },
    { at: 263, tier: 2, q: "Over mountains and forests and _____", options: ["seas", "rivers", "valleys", "lakes"], correct: 0 },

    { at: 271, tier: 1, q: "Flying high, high, I'm a bird in the _____", options: ["sky", "air", "clouds", "wind"], correct: 0 },
    { at: 279, tier: 2, q: "(I'm an _____)", options: ["eagle", "angel", "bird", "aviator"], correct: 0 },
    { at: 286, tier: 2, q: "I'm an eagle that rides on the _____", options: ["breeze", "wind", "air", "cloud"], correct: 0 },
    { at: 294, tier: 1, q: "High, high, what a feeling to _____", options: ["fly", "soar", "rise", "float"], correct: 0 },
    { at: 301, tier: 2, q: "(What a _____)", options: ["feeling", "dream", "sight", "joy"], correct: 0 },
    { at: 308, tier: 2, q: "Over mountains and forests and _____", options: ["seas", "rivers", "valleys", "lakes"], correct: 0 },
    { at: 316, tier: 2, q: "And to go anywhere that I _____", options: ["please", "want", "choose", "can"], correct: 0 }
  ]
},
   {
  id: "abba-fernando",
  questId: "Quest Video 39",
  category: "ABBA",
  difficulty: "Intermediate",
  title: "ABBA - Fernando (Lyrics)",
  youtubeId: "dQsjAbZDx-4",
  durationHint: 276,
  description: "ABBA's evocative classic 'Fernando', recalling friendship, conflict, and the fight for freedom.",
  questions: [
    { at: 0,   tier: 1, q: "Can you hear the drums _____?", options: ["Fernando", "tonight", "again", "calling"], correct: 0 },
    { at: 7,   tier: 2, q: "I remember long ago another starry _____ like this", options: ["night", "evening", "day", "time"], correct: 0 },
    { at: 15,  tier: 2, q: "In the firelight _____", options: ["Fernando", "my friend", "tonight", "old friend"], correct: 0 },
    { at: 23,  tier: 3, q: "You were humming to yourself and softly strumming your _____", options: ["guitar", "lute", "banjo", "strings"], correct: 0 },
    { at: 32,  tier: 2, q: "I could hear the distant _____", options: ["drums", "voices", "guns", "music"], correct: 0 },
    { at: 40,  tier: 3, q: "And sounds of bugle calls were coming from _____", options: ["afar", "outside", "behind", "above"], correct: 0 },

    { at: 51,  tier: 2, q: "They were closer now _____", options: ["Fernando", "my friend", "old friend", "tonight"], correct: 0 },
    { at: 58,  tier: 2, q: "Every hour every minute seemed to last _____", options: ["eternally", "forever", "endlessly", "slowly"], correct: 0 },
    { at: 67,  tier: 2, q: "I was so afraid _____", options: ["Fernando", "my friend", "that night", "then"], correct: 0 },
    { at: 75,  tier: 3, q: "We were young and full of life and none of us prepared to _____", options: ["die", "fight", "run", "leave"], correct: 0 },
    { at: 84,  tier: 2, q: "And I'm not ashamed to _____", options: ["say", "cry", "admit", "tell"], correct: 0 },
    { at: 91,  tier: 3, q: "The roar of guns and cannons almost made me _____", options: ["cry", "run", "fall", "hide"], correct: 0 },

    { at: 104, tier: 3, q: "There was something in the _____ that night", options: ["air", "wind", "sky", "dark"], correct: 0 },
    { at: 112, tier: 1, q: "The stars were bright, _____", options: ["Fernando", "my friend", "tonight", "old friend"], correct: 0 },
    { at: 120, tier: 2, q: "They were shining there for you and _____", options: ["me", "us", "everyone", "Fernando"], correct: 0 },
    { at: 128, tier: 2, q: "For liberty, _____", options: ["Fernando", "my friend", "tonight", "old friend"], correct: 0 },
    { at: 136, tier: 3, q: "Though I never thought that we could _____", options: ["lose", "die", "fail", "fall"], correct: 0 },
    { at: 143, tier: 1, q: "There's no _____", options: ["regret", "fear", "shame", "doubt"], correct: 0 },
    { at: 150, tier: 3, q: "If I had to do the same _____", options: ["again", "thing", "fight", "way"], correct: 0 },
    { at: 158, tier: 2, q: "I would, my _____, Fernando", options: ["friend", "brother", "companion", "comrade"], correct: 0 },
    { at: 166, tier: 3, q: "If I had to do the same again", options: ["I would", "I could", "I should", "I might"], correct: 0 },
    { at: 174, tier: 2, q: "I would, my _____, Fernando", options: ["friend", "brother", "companion", "comrade"], correct: 0 },

    { at: 187, tier: 2, q: "Now we're old and _____ Fernando", options: ["grey", "tired", "wise", "older"], correct: 0 },
    { at: 196, tier: 3, q: "And since many years I haven't seen a _____ in your hand", options: ["rifle", "gun", "weapon", "sword"], correct: 0 },
    { at: 207, tier: 1, q: "Can you hear the drums _____?", options: ["Fernando", "tonight", "again", "calling"], correct: 0 },
    { at: 215, tier: 3, q: "Do you still recall the frightful night we crossed the Rio _____?", options: ["Grande", "Bravo", "Negro", "Blanco"], correct: 0 },
    { at: 226, tier: 2, q: "I can see it in your _____", options: ["eyes", "face", "heart", "smile"], correct: 0 },
    { at: 234, tier: 3, q: "How proud you were to fight for freedom in this _____", options: ["land", "country", "world", "place"], correct: 0 },

    { at: 247, tier: 3, q: "There was something in the _____ that night", options: ["air", "wind", "sky", "dark"], correct: 0 },
    { at: 255, tier: 1, q: "The stars were bright, _____", options: ["Fernando", "my friend", "tonight", "old friend"], correct: 0 },
    { at: 263, tier: 2, q: "They were shining there for you and _____", options: ["me", "us", "everyone", "Fernando"], correct: 0 },
    { at: 271, tier: 2, q: "For liberty, _____", options: ["Fernando", "my friend", "tonight", "old friend"], correct: 0 },
    { at: 279, tier: 3, q: "Though I never thought that we could _____", options: ["lose", "die", "fail", "fall"], correct: 0 },
    { at: 286, tier: 1, q: "There's no _____", options: ["regret", "fear", "shame", "doubt"], correct: 0 },
    { at: 293, tier: 3, q: "If I had to do the same _____", options: ["again", "thing", "fight", "way"], correct: 0 },
    { at: 301, tier: 2, q: "I would, my _____, Fernando", options: ["friend", "brother", "companion", "comrade"], correct: 0 },

    { at: 312, tier: 3, q: "Yes, if I had to do the same _____", options: ["again", "thing", "fight", "way"], correct: 0 },
    { at: 320, tier: 2, q: "I would, my _____, Fernando...", options: ["friend", "brother", "companion", "comrade"], correct: 0 }
  ]
},
   {
  id: "abba-chiquitita",
  questId: "Quest Video 40",
  category: "ABBA",
  difficulty: "Intermediate",
  title: "ABBA - Chiquitita (Lyrics)",
  youtubeId: "p4QqMKe3rwY",
  durationHint: 320,
  description: "ABBA's uplifting classic 'Chiquitita', offering comfort and encouragement to a friend in sorrow.",
  questions: [
    { at: 0,   tier: 1, q: "Chiquitita, tell me what's _____", options: ["wrong", "right", "happened", "missing"], correct: 0 },
    { at: 7,   tier: 3, q: "You're enchained by your own _____", options: ["sorrow", "sadness", "fear", "pain"], correct: 0 },
    { at: 14,  tier: 2, q: "In your eyes there is no hope for _____", options: ["tomorrow", "today", "the future", "happiness"], correct: 0 },

    { at: 27,  tier: 2, q: "How I hate to see you like _____", options: ["this", "that", "that way", "so"], correct: 0 },
    { at: 34,  tier: 2, q: "There is no way you can _____ it", options: ["deny", "hide", "change", "forget"], correct: 0 },
    { at: 41,  tier: 2, q: "I can see that you're oh so sad, so _____", options: ["quiet", "lonely", "silent", "still"], correct: 0 },

    { at: 53,  tier: 1, q: "Chiquitita, tell me the _____", options: ["truth", "answer", "story", "reason"], correct: 0 },
    { at: 60,  tier: 2, q: "I'm a shoulder you can _____ on", options: ["cry", "lean", "rest", "depend"], correct: 0 },
    { at: 67,  tier: 2, q: "Your best friend, I'm the one you must rely _____", options: ["on", "upon", "with", "to"], correct: 0 },

    { at: 80,  tier: 2, q: "You were always sure of _____", options: ["yourself", "everything", "your way", "the answer"], correct: 0 },
    { at: 87,  tier: 3, q: "Now I see you've broken a _____", options: ["feather", "wing", "heart", "promise"], correct: 0 },
    { at: 94,  tier: 2, q: "I hope we can patch it up _____", options: ["together", "again", "somehow", "soon"], correct: 0 },

    { at: 107, tier: 1, q: "Chiquitita, you and I _____", options: ["know", "cry", "see", "feel"], correct: 0 },
    { at: 115, tier: 3, q: "How the heartaches come and they go and the scars they're _____", options: ["leavin'", "leaving", "making", "hiding"], correct: 0 },
    { at: 125, tier: 2, q: "You'll be dancing once again and the _____ will end", options: ["pain", "sorrow", "heartache", "tears"], correct: 0 },
    { at: 134, tier: 2, q: "You would have no time for _____", options: ["grievin'", "crying", "sorrow", "sadness"], correct: 0 },

    { at: 148, tier: 1, q: "Chiquitita, you and I _____", options: ["cry", "know", "dance", "sing"], correct: 0 },
    { at: 156, tier: 2, q: "But the sun is still in the _____", options: ["sky", "air", "morning", "distance"], correct: 0 },
    { at: 164, tier: 2, q: "And shinin' _____ you", options: ["above", "around", "beside", "over"], correct: 0 },
    { at: 172, tier: 3, q: "Let me hear you sing once more like you did _____", options: ["before", "then", "yesterday", "once"], correct: 0 },
    { at: 181, tier: 1, q: "Sing a new _____, Chiquitita", options: ["song", "tune", "melody", "verse"], correct: 0 },

    { at: 194, tier: 2, q: "Try once more like you did _____", options: ["before", "then", "yesterday", "once"], correct: 0 },
    { at: 202, tier: 1, q: "Sing a new song, _____", options: ["Chiquitita", "Fernando", "darling", "my friend"], correct: 0 },

    { at: 215, tier: 2, q: "So the walls came tumblin' _____", options: ["down", "apart", "away", "over"], correct: 0 },
    { at: 223, tier: 3, q: "And your love's a blown out _____", options: ["candle", "fire", "flame", "light"], correct: 0 },
    { at: 231, tier: 2, q: "All is gone and it seems too hard to _____", options: ["handle", "bear", "accept", "forget"], correct: 0 },

    { at: 244, tier: 1, q: "Chiquitita, tell me the _____", options: ["truth", "answer", "story", "reason"], correct: 0 },
    { at: 251, tier: 2, q: "There is no way you can _____ it", options: ["deny", "hide", "change", "forget"], correct: 0 },
    { at: 258, tier: 2, q: "I see that you're oh so sad, so _____", options: ["quiet", "lonely", "silent", "still"], correct: 0 },

    { at: 271, tier: 1, q: "Chiquitita, you and I _____", options: ["know", "cry", "see", "feel"], correct: 0 },
    { at: 279, tier: 3, q: "How the heartaches come and they go and the scars they're _____", options: ["leavin'", "leaving", "making", "hiding"], correct: 0 },
    { at: 289, tier: 2, q: "You'll be dancin' once again and the _____ will end", options: ["pain", "sorrow", "heartache", "tears"], correct: 0 },
    { at: 298, tier: 2, q: "You will have no time for _____", options: ["grievin'", "crying", "sorrow", "sadness"], correct: 0 },

    { at: 311, tier: 1, q: "Chiquitita, you and I _____", options: ["cry", "know", "dance", "sing"], correct: 0 },
    { at: 319, tier: 2, q: "But the sun is still in the _____", options: ["sky", "air", "morning", "distance"], correct: 0 },
    { at: 327, tier: 2, q: "And shinin' _____ you", options: ["above", "around", "beside", "over"], correct: 0 },
    { at: 335, tier: 3, q: "Let me hear you sing once more like you did _____", options: ["before", "then", "yesterday", "once"], correct: 0 },
    { at: 344, tier: 1, q: "Sing a new _____, Chiquitita", options: ["song", "tune", "melody", "verse"], correct: 0 },

    { at: 357, tier: 2, q: "Try once more like you did _____", options: ["before", "then", "yesterday", "once"], correct: 0 },
    { at: 365, tier: 1, q: "Sing a new song, _____", options: ["Chiquitita", "Fernando", "darling", "my friend"], correct: 0 },
    { at: 374, tier: 2, q: "Try once more like you did _____", options: ["before", "then", "yesterday", "once"], correct: 0 },
    { at: 382, tier: 1, q: "Sing a new song, _____", options: ["Chiquitita", "Fernando", "darling", "my friend"], correct: 0 }
  ]
},
   {
  id: "abba-i-have-a-dream",
  questId: "Quest Video 41",
  category: "ABBA",
  difficulty: "Intermediate",
  title: "ABBA - I Have a Dream (Lyrics)",
  youtubeId: "9p9JxQqWq4E",
  durationHint: 277,
  description: "ABBA's inspirational classic 'I Have a Dream', about hope, imagination, perseverance, and believing in something better.",
  questions: [
    { at: 0,   tier: 1, q: "I have a _____, a song to sing", options: ["dream", "wish", "plan", "hope"], correct: 0 },
    { at: 7,   tier: 2, q: "To help me cope with _____", options: ["anything", "everything", "reality", "life"], correct: 0 },
    { at: 15,  tier: 3, q: "If you see the wonder of a _____ tale", options: ["fairy", "folk", "love", "magic"], correct: 0 },
    { at: 23,  tier: 3, q: "You can take the future even if you _____", options: ["fail", "fall", "lose", "try"], correct: 0 },
    { at: 32,  tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 40,  tier: 3, q: "Something good in everything I _____", options: ["see", "know", "feel", "find"], correct: 0 },
    { at: 49,  tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 57,  tier: 3, q: "When I know the time is right for _____", options: ["me", "us", "now", "this"], correct: 0 },
    { at: 65,  tier: 2, q: "I'll cross the _____ - I have a dream", options: ["stream", "river", "bridge", "water"], correct: 0 },

    { at: 77,  tier: 1, q: "I have a _____, a fantasy", options: ["dream", "wish", "plan", "hope"], correct: 0 },
    { at: 85,  tier: 2, q: "To help me through _____", options: ["reality", "anything", "life", "darkness"], correct: 0 },
    { at: 94,  tier: 3, q: "And my destination makes it worth the _____", options: ["while", "journey", "effort", "time"], correct: 0 },
    { at: 103, tier: 3, q: "Pushing through the darkness still another _____", options: ["mile", "day", "step", "time"], correct: 0 },
    { at: 113, tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 121, tier: 3, q: "Something good in everything I _____", options: ["see", "know", "feel", "find"], correct: 0 },
    { at: 130, tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 138, tier: 3, q: "When I know the time is right for _____", options: ["me", "us", "now", "this"], correct: 0 },
    { at: 146, tier: 2, q: "I'll cross the _____ - I have a dream", options: ["stream", "river", "bridge", "water"], correct: 0 },
    { at: 155, tier: 2, q: "I'll cross the stream - I have a _____", options: ["dream", "fantasy", "hope", "wish"], correct: 0 },

    { at: 169, tier: 1, q: "I have a _____, a song to sing", options: ["dream", "wish", "plan", "hope"], correct: 0 },
    { at: 177, tier: 2, q: "To help me cope with _____", options: ["anything", "everything", "reality", "life"], correct: 0 },
    { at: 185, tier: 3, q: "If you see the wonder of a _____ tale", options: ["fairy", "folk", "love", "magic"], correct: 0 },
    { at: 193, tier: 3, q: "You can take the future even if you _____", options: ["fail", "fall", "lose", "try"], correct: 0 },
    { at: 202, tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 210, tier: 3, q: "Something good in everything I _____", options: ["see", "know", "feel", "find"], correct: 0 },
    { at: 219, tier: 1, q: "I believe in _____", options: ["angels", "dreams", "miracles", "magic"], correct: 0 },
    { at: 227, tier: 3, q: "When I know the time is right for _____", options: ["me", "us", "now", "this"], correct: 0 },
    { at: 235, tier: 2, q: "I'll cross the _____ - I have a dream", options: ["stream", "river", "bridge", "water"], correct: 0 },
    { at: 244, tier: 2, q: "I'll cross the stream - I have a _____", options: ["dream", "fantasy", "hope", "wish"], correct: 0 }
  ]
}
];
